### ISSUE TITLE
Django 1.11 and Python 3+

### ISSUE THREAD

**Issue by BallisticPain** [GetStream/stream-django#100]
I'm currently running Django 1.11.latest and Python 3.8+. Due to this [line](https://github.com/GetStream/stream-django/blob/6717bd1be6d03b0a9c9b78a5b1f56f01d30eaee3/setup.py#L9) and the 3 following lines I have an error when `Pipenv` is attempting to update my dependencies. Only recently have I figured out it was `stream-django` due to `Pipenv` finally letting me know which package was causing the ruckus.

I believe changing this [line](https://github.com/GetStream/stream-django/blob/6717bd1be6d03b0a9c9b78a5b1f56f01d30eaee3/setup.py#L12) to the following would do the trick...
```
    django = 'django>=1.11.29,<3.2'  # checked https://docs.djangoproject.com/en/dev/releases/3.1/#backwards-incompatible-3-1
```

I will submit a PR after posting this issue. Let me know if I need to make any subsequent changes.

Thanks!!
Jarvis

**Comment by ferhatelmas** [comment]
should be good now.
