### ISSUE TITLE
Django 3.2 LTS support ?

### ISSUE THREAD

**Issue by tkrevh** [GetStream/stream-django#107]
Hello!

We're already using your chat, and are now starting to build functionalities around feeds as well.
Mainstream support for Django 3.1 expired in April this year (and extended one expires in December this year).
Django 3.2 is an LTS version, meaning it's expiring in April 2024.
Any chance you could bump up the version to Django 3.2?

**Comment by ferhatelmas** [comment]
Definitely, we will do it ASAP.

**Comment by tkrevh** [comment]
@ferhatelmas any update on this? This is really high priority for us and it only requires a minimal change in
https://github.com/GetStream/stream-django/blob/611e31f8f1940e9c9ac4f3f49a820f3b2663c2b5/setup.py#L12

to: `django = "django>=2.0,<=3.2"`

**Comment by ferhatelmas** [comment]
On it, you should be able to use by tomorrow. Sorry for the latency.

**Comment by tkrevh** [comment]
Thank you @ferhatelmas, we appreciate you 👏

**Comment by ferhatelmas** [comment]
https://github.com/GetStream/stream-django/releases/tag/1.7.0

let me know if you see any issues.

**Comment by tkrevh** [comment]
@ferhatelmas yes, unfortuantely there is a serious issue - now django 3.2 can no longer start:
`\lib\site-packages\stream_django\__init__.py", line 4, in <module>
    major, minor, _ = (int(i) for i in django.__version__.split('.'))
ValueError: not enough values to unpack (expected 3, got 2)`

Code is trying to unpack version 3.2 into three variables (underscore being the third one) and it fails on '3.2' string.
I would suggest replacing current line:
https://github.com/GetStream/stream-django/blob/7496b0d620027c7e2ca1fc2d63d9e10064fb8c54/stream_django/__init__.py#L4

With:

```
version_list = [int(i) for i in django.__version__.split('.')]
major, minor = version_list[0], version_list[1]

```

**Comment by tkrevh** [comment]
I've also created a PR #109 for it
