### ISSUE TITLE
Django 4 support

### ISSUE THREAD

**Issue by metamatik** [GetStream/stream-django#111]
Hello,

First of all, thanks a lot for your work on this project :)

We are currently using `stream-django` on an application which we are planning to bump to Django 4.

I see that you have already updated the project to support it a few months ago, but unless I am mistaken there hasn't been a PyPI release yet for this change.

Is such a release planned in the near future?
If not, is there something we might be able to do to help?

Thanks in advance ^^

**Comment by rustanacexd** [comment]
+1

**Comment by ferhatelmas** [comment]
1.8.0 had been released. Closing this but if you have seen any issues, please let us know.
