### ISSUE TITLE
RemovedInDjango19Warning: django.db.models.loading deprecated

### ISSUE THREAD

**Issue by JJZolper** [GetStream/stream-django#19]
Basically, I'm getting:

/Users/JJZ/.virtualenvs/athletesunited/lib/python3.4/importlib/_bootstrap.py:321: RemovedInDjango19Warning: The utilities in django.db.models.loading are deprecated in favor of the new application loading system.
  return f(*args, **kwds)

And I see in enrich.py:

from django.db.models.loading import get_model

Django now has apps:

https://docs.djangoproject.com/en/1.8/ref/applications/

so

try:
    from django.apps import apps
    get_model = apps.get_model
except ImportError:
    from django.db.models.loading import get_model

should do it.

Thanks,

JJ

**Comment by JJZolper** [comment]
But actually you should probably add the apps.py file and set that up, let me know if you need help as I think I got my stuff working. It just takes a little reading before you totally understand what they want. You should be able to set it so our Installed Apps doesn't change also, it confused me for a bit but I assume that applies to apps like this and not to my internal work. We should just be able to leave it as "stream_django".

**Comment by tbarbugli** [comment]
Hi JJ,

Thank you for reporting this issue and for the extra details. I am going to have a look at this next week. How did you solve the problem in your case?

**Comment by JJZolper** [comment]
Yeah absolutely sure thing. And sounds good I look forward to the updates. Oh well I gave you all that you need. I'd try giving a crack at it first but if you hit some snags we can see if I have some advice that helps. I also gave you what I believe is the solution for the models loading warning for 1.9. It is loaded from apps as shown from the try block. As for the rest of it, the documentation that I shared on the link is your best bet. As stream django is a public package people install and use as third party your situation will be different then mine. My situation is a private package and so I am flexible in terms of how with this new django apps concept in how I set my installed apps etc. I believe like I said you can design it so people who install stream django wont have to change their installed apps setting, i believe it is the init.py file. The caveat is i hacked out all my init.py files because i'm running on python 3. I suggest you design stream django so it supports both py2 and py3 and that will drive how the django "app" refactoring goes.

**Comment by JJZolper** [comment]
how's it going so far? alright?

**Comment by tbarbugli** [comment]
warning is fixed on 1.2.1
