### ISSUE TITLE
pip install is broken

### ISSUE THREAD

**Issue by picturedots** [GetStream/stream-django#22]
I can't install with pip -- it looks like the problem is that the required version of httpsig is no longer available.

Pip error message:
Could not find any downloads that satisfy the requirement httpsig==1.1.0 (from stream-python>=2.1.3-    >stream-django)

And here's the status of httpsig:
$ yolk -V httpsig
httpsig 1.1.2

**Comment by tbarbugli** [comment]
httpsig 1.1.0 is available on pypi (
https://pypi.python.org/pypi/httpsig/1.1.0). what version of pip are you
using to install the package?
ᐧ
