### ISSUE TITLE
A method to add activity using the feed manager

### ISSUE THREAD

**Issue by github-account-because-they-want-it** [GetStream/stream-django#23]
To create my activities, I've been using the raw `client.stream_client` to add activities. But for them to be ready for enrichment, I'm afraid they activity data should have a specific format. Is there a method on the feed manager to do it?. I can't see it anywhere.

**Comment by tbarbugli** [comment]
can you elaborate more on the data that you have in your activities? the library can handle serialization and enrichment of Django models, other object can be supported by extending the Enricher class. I can give you some concrete help once I know more about that ;) just for my curiosity, why do you need to use the stream client directly?

**Comment by github-account-because-they-want-it** [comment]
I used the stream client directly because I couldn't find a method on the feed manager to add activities. That was my question. Is there a method on the feed manager to add activities?.
Here's how I used the raw stream client:

```python
user_feed = stream_client.feed("user", request.user.id)
    user_feed.add_activity({"actor": request.user.username, "verb": "publish",
                            "object": "Video:{}".format(instance.id),
                            "title": instance.title})
```
Since we don't maintain a model for that action, I tried to use the stream client directly to add activities.
What can work in my use case?

**Comment by tbarbugli** [comment]
I think you can take advantage of the library and do something like this:

```python
from stream_django.activity import create_reference
from stream_django.feed_manager import feed_manager


user_feed = manager.get_user_feed(request.user.id)
obj_ref = create_reference(instance)
actor_ref = create_reference(request.user) 
user_feed.add_activity({"actor": actor_ref, "verb": "publish",
                            "object": obj_ref,
                            "title": instance.title})
```

This is assuming that you have a Video model of course, if not please add some more information about your use case.

**Comment by github-account-because-they-want-it** [comment]
Thank you @tbarbugli. That worked.
