### ISSUE TITLE
FeedConfigException: The following feeds are not configured: 'user'

### ISSUE THREAD

**Issue by jaineshp** [GetStream/stream-django#24]
```
>>> user=User.objects.get(id=1)
>>> feed=feed_manager.get_user_feed(user.id) 
>>> activity=feed.get(limit=25)['results']

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/stream/feed.py", line 119, in get
    self.feed_url, params=params, signature=token)
  File "/usr/local/lib/python2.7/dist-packages/stream/client.py", line 192, in get
    return self._make_request(self.session.get, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/stream/client.py", line 153, in _make_request
    return self._parse_response(response)
  File "/usr/local/lib/python2.7/dist-packages/stream/client.py", line 110, in _parse_response
    self.raise_exception(parsed_result, status_code=response.status_code)
  File "/usr/local/lib/python2.7/dist-packages/stream/client.py", line 180, in raise_exception
    raise exception
FeedConfigException: The following feeds are not configured: 'user'
```

**Comment by tbarbugli** [comment]
did you create the user feed from the dashboard? perhaps you created a new app but not the feeds used by the library (user,flat,aggregated,notification feeds)

**Comment by jaineshp** [comment]
Am not getting it. What is feeds used by the library?
I have three classes say Question and Upvote. What do I need to create in the dashboard

**Comment by tbarbugli** [comment]
django-stream uses the 4 default feed types (user,flat,aggregated and
notification). When an activity models is saved, the library sends an
activity to the user feed. When a user follows another user, flat and
aggregated feeds are connected to the user feed.

The library expects this feeds types to be defined in the dashboard,
perhaps you deleted them or you created a new app from the dashboard that
does not have these feeds.

Best,
Tommaso

**Comment by jaineshp** [comment]
Means I have to create 4 feeds? And what about feed slugs?

**Comment by tbarbugli** [comment]
Feed slugs will be: "user", "flat", "aggregated" and "notification"

If you are not planning to use aggregated feeds and notification feeds, you
can avoid creating them (just remember to update stream-django settings
accordingly https://github.com/GetStream/stream-django/#settings)

Best,
Tommaso

**Comment by JelteF** [comment]
Closing this, the supplied error is also clearer now.
