### ISSUE TITLE
Support for celery or other asynchronous queues?

### ISSUE THREAD

**Issue by sampeka** [GetStream/stream-django#25]
Hi, I'm just considering whether or not to use this app or to create something in-house. Is celery supported or is it possible to build in some support for it through some middleware? When creating models aren't page load-times increased because of the network io -  or have you already built in some asynchronous processing?

**Comment by tbarbugli** [comment]
Hi there,
doing celery outside of the http request is indeed a good practice. You can easily use celery for that by subclassing the default manager (https://github.com/GetStream/stream-django/blob/master/stream_django/managers.py) and change the STREAM_FEED_MANAGER_CLASS setting accordingly.

**Comment by sampeka** [comment]
Thanks a lot - makes sense. And a quick extra question (can create another issue if you'd prefer). In the docs you mentioned the `Activity.activity_related_models` fields will be used in a call to `select_related` to retrieve the objects. Is it possible to specify any fields to be retrieved with `prefetch_related`? Something like a generic Tag or Like will usually need the content_object to be retrieved alongside it.

**Comment by tbarbugli** [comment]
There is not direct support for `prefetch_related` but you can get it done by implementing a hook function in your enricher subclass. You can see the relevant part where the hook is looked up here: https://github.com/GetStream/stream-django/blob/master/stream_django/enrich.py#L90

If you model is called `Tag` you need to implement a method called `fetch_tag_instances`

eg.

```python
from stream_django.enrich import Enrich

class MyEnrich(Enrich):

    def fetch_tag_instances(self, pks):
        return Tag.objects. in_bulk(pks).select_related(...).prefetch_related(...)
```

**Comment by sampeka** [comment]
Thanks a lot :+1:
