### ISSUE TITLE
Get all users that are subscribed to a feed

### ISSUE THREAD

**Issue by rawbeans** [GetStream/stream-django#28]
I can't find a way to get all users that are subscribed to a feed. 

In relation to the twitter example, how do you get a list of users following another user?

**Comment by tbarbugli** [comment]
in the Twitter example app, followers are stored in the database (https://github.com/GetStream/django_twitter/blob/master/stream_twitter/models.py#L68)

so you can easily pull this information via the ORM:

```python
user.friends.all()
user.followers.all()
```

alternatively you can get the same information using the

**Comment by rawbeans** [comment]
@tbarbugli 
Out of curiosity, what is the alternative method of getting the same information?

You didn't complete your sentence. Thanks.

**Comment by tbarbugli** [comment]
@rawbeans updated my comment with the missing part
