### ISSUE TITLE
Must implement activity_object_attr

### ISSUE THREAD

**Issue by jacobwindsor** [GetStream/stream-django#33]
Not sure if this is just me but it seems that the `NotImplementedError` that gives "Must implement activity_object_attr" is always thrown. 

The property is defined in "activity.py" but will always throw the error unless the property is defined in the desired model with `return self`.  Not sure why this is done this way and `return self` isn't just written in the mixin. 

I am sure the docs should be updated if what I have is correct or "activity.py" be updated

**Comment by tbarbugli** [comment]
perhaps returning self is the best default behavior. feel free to make a PR for it otherwise we'll fix this on next release!

**Comment by pterk** [comment]
@tbarbugli already did it ages ago. Probably forgot to close this issue?
