### ISSUE TITLE
Low level Api : follow_many() got an unexpected keyword argument 'activity_copy_limit'

### ISSUE THREAD

**Issue by X17** [GetStream/stream-django#41]
```
from stream_django.client import stream_client

follows = [
  {'source': 'group:1', 'target': 'user:1'}, 
  {'source': 'group:1', 'target': 'user:2'},
 ]

stream_client.follow_many(follows,activity_copy_limit=10)
```

**Error**
Traceback (most recent call last):
  File "<console>", line 1, in <module>
TypeError: follow_many() got an unexpected keyword argument 'activity_copy_limit'

**Comment by tbarbugli** [comment]
moving this to the stream-python project https://github.com/GetStream/stream-python/issues/40
