### ISSUE TITLE
Get total follower/following counts

### ISSUE THREAD

**Issue by jacobwindsor** [GetStream/stream-django#42]
Currently the methods for getting the followers/following objects (using the feed_manager and stream_client classes) only returns the paginated list of items and not a count, this isn't very useful if you need to find the number of followers/following.

Currently:

```
{'results': [...], 'duration':'some_ms'}
```

**Comment by cklar** [comment]
If I understood the REST API correct, then this information is not provided at all. 
Therefore I should be an enhancement of the GetStream platform and not of the django client.

**Comment by japrogramer** [comment]
I also need this, has the enhancement been made to the GetStream platform?

**Comment by dwightgunning** [comment]
Thanks for the interest. This is still on our long-range backlog.

**Comment by dzero1** [comment]
Any update on this? I like to have this with serverside code

**Comment by ferhatelmas** [comment]
Yes, it's possible via `stream_client`.

```py
client.follow_stats(feed_id)
```
