### ISSUE TITLE
raise_exception() not returning exception details

### ISSUE THREAD

**Issue by boulderdave** [GetStream/stream-django#43]
I received the following traceback when trying to add an activity, with an empty exception message: http://dpaste.com/0J16QNB

After digging into it deeper, I discovered that `result` contained the following:

`{u'exception': u'InputException', u'code': 4, u'status_code': 400, u'detail': u"Errors for fields 'verb'", u'duration': u'10ms', u'exception_fields': {u'verb': [u'Ensure this value has at most 20 characters (it has 26).', u'Field "verb" errors: [u\'Ensure this value has at most 20 characters (it has 26).\']']}}`

As you can see - it was a simple issue - my verb was too long.
However, raise_exception was unable to return that information to me. 

`errors = errors_from_fields(exception_fields)` does not property parse `exception_fields`, which is:
`{u'verb': [u'Ensure this value has at most 20 characters (it has 26).', u'Field "verb" errors: [u\'Ensure this value has at most 20 characters (it has 26).\']']}`

The function returns `[]`, which is not correct.

**Comment by JelteF** [comment]
This is a bug in the undelying python library https://github.com/GetStream/stream-python/pull/52

**Comment by JelteF** [comment]
The pull request was merged and released, so it should be fixed now.
