### ISSUE TITLE
'flat' feeds are not configured

### ISSUE THREAD

**Issue by scotthou94** [GetStream/stream-django#44]
Right now I have the functional feeds for each user's own tweet, but when I try to follow another user, it gave me this error: `The following feeds are not configured: flat`.
I tried to create the `Follow` object in the shell by `follow = Follow.objects.create(user=one, target=two)`, and then the above error was thrown.
Any idea what went wrong? Thanks in advance.

**Comment by tbarbugli** [comment]
what version of stream-django are you using?

**Comment by scotthou94** [comment]
ver. 1.2.6

2016-09-04 19:53 GMT+08:00 Tommaso Barbugli <notifications@github.com>:

**Comment by tbarbugli** [comment]
you should upgrade the library to the latest version (1.3.1)

**Comment by scotthou94** [comment]
@tbarbugli will `pip install stream_django --upgrade` suffice?

**Comment by scotthou94** [comment]
@tbarbugli after upgrading to the latest version 1.3.1, I could create `Follow` objects from the shell and in the discover page the status of the target user says `unfollow` which is correct.
But still I get this `The following feeds are not configured: flat` error, and no feeds of the target user is shown. In the getstream.io explorer I can't find any follow data, so does it have to do with the getstream app configuration??

**Comment by tbarbugli** [comment]
What configs do you have in settings.py for getstream?

**Comment by scotthou94** [comment]
```python
STREAM_API_KEY = 'key'
STREAM_API_SECRET = 'secret'
STREAM_NEWS_FEEDS = dict(flat='flat')
```

**Comment by tbarbugli** [comment]
the last one is wrong, it should be: 

`STREAM_NEWS_FEEDS = dict(timeline='timeline')`

Did you copy this from somewhere? Perhaps we have some reference to that in an old example/page?

**Comment by scotthou94** [comment]
I think I read it from the tutorial.

2016-09-06 18:50 GMT+08:00 Tommaso Barbugli <notifications@github.com>:

**Comment by scotthou94** [comment]
Thanks for the reply, it solved that error and I can find follow data in the getstream explorer. But I still didn't get the target's feed .
Here's the signal receiver code:
```python
def unfollow_feed(sender, instance, **kwargs):
    feed_manager.unfollow_user(instance.user_id, instance.target_id)

def follow_feed(sender, instance, created, **kwargs):
    if created:
        feed_manager.follow_user(instance.user_id, instance.target_id)

post_save.connect(follow_feed, sender=Follow)
post_delete.connect(unfollow_feed, sender=Follow)
```
As I understand when a follow object is created the above codes should perform the actual follow action right ?  How come the follower don't get the feed ?

**Comment by tbarbugli** [comment]
what do you mean with "the follower doesnt get the feed?"

**Comment by scotthou94** [comment]
A user could only see his own tweet, even though he follows someone.

2016-09-07 22:46 GMT+08:00 Tommaso Barbugli <notifications@github.com>:

**Comment by tbarbugli** [comment]
did you check on Stream's Dashboard if the follow relationship was created?

**Comment by scotthou94** [comment]
yes, the follow relationship is created

2016-09-08 15:09 GMT+08:00 Tommaso Barbugli <notifications@github.com>:

**Comment by scotthou94** [comment]
yes, the follow relationship is created
here's a screenshot of the dashboard
![follow](https://cloud.githubusercontent.com/assets/17608374/18348275/ff66fc24-75fc-11e6-8802-6e1857b5c802.png)
