### ISSUE TITLE
How to adjust the timezone  on getstream feeds

### ISSUE THREAD

**Issue by maan19** [GetStream/stream-django#46]

**Comment by tbarbugli** [comment]
I guess you refer to the `time` field of activities. Stream stores that in UTC, it's very simple to display that using your locale settings.

**Comment by lggwettmann** [comment]
How would you easily tackle this? Just using the localtime template filter doesn't work - so I assume one needs to make the naive datetime timezone aware to be able to use the template filter first.

How/Where would I do that best?

**Comment by tbarbugli** [comment]
linking to API client issue: https://github.com/GetStream/stream-python/issues/108

**Comment by tbarbugli** [comment]
atm the solution is to localize the activity.time field before sending it to the template 

```python
import pytz

response = feed.get()
for activity in response:
    activity["time"] = pytz.UTC.localize(activity["time"])
```

**Comment by lggwettmann** [comment]
Thanks, @tbarbugli for the fantastic help!
