### ISSUE TITLE
Target is not enriched anymore (Update from Stream-django 1.3.1 and Stream-python 2.3.9)

### ISSUE THREAD

**Issue by lggwettmann** [GetStream/stream-django#75]
Hi guys,

I just updated from stream-django 1.3.1 to 1.4.0 and stream-python 2.3.9 to 2.8.1 and suddenly only my target is not enriched anymore and stays in the template as string 'courses.Course:1' -- What changed? Is there any migration info? I've been looking for hours to find the change.

**Comment by tbarbugli** [comment]
AFAIK target was never enriched out of the box by the enricher class, did you find out in the end the cause of this?

**Comment by lggwettmann** [comment]
Hey @tbarbugli,

thanks for answering and I think the issue is just that I seem to (still) have no clue how to enrich targets. I just tried to add 'target' in the enricher instantiation in the view which didn't work. And would not know how to extend the enricher to include targets:
```
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        enricher = Enrich(('actor', 'object', 'target',))
        feed = feed_manager.get_user_feed(self.get_feed_user().id)
        activities = feed.get(limit=25)['results']
        enricher.enrich_activities(activities)
        context.update({'user_feed': activities})
        return context
```

Any pointers on this? It's a miracle to me that I'm the only one struggling with this.. Did I overlook something?

**Comment by lggwettmann** [comment]
Okay, I found it. 😅 

One basically has to include the target in the extra_activity_data and then the target gets enriched. It would be great if that could mentioned somewhere in the ReadMe. It wasn't obvious to me at all as I see 'target' as quite a standard object to be added in the activity data if it's defined in the model - if that makes any sense?

Thanks for the great package.
