### ISSUE TITLE
React frontend examples?

### ISSUE THREAD

**Issue by japrogramer** [GetStream/stream-django#77]
Hi I have walked thru the examples that use the django templating engine, however since the activities are rendered thru a tag on the server side, determining which template to include per activity, it becomes difficult to do that from a reactive front end.

Are there any examples or code snippets that would show me how to select which component to use while reading the activity stream .. and how would that data be sent .. considering that the enriched data might need access to fks or m2ms?

**Comment by japrogramer** [comment]
Unless I could assign a serializer per activity type, than I could see how I could get the info I need. Similar to how now each activity needs a template.

**Comment by japrogramer** [comment]
@dwightgunning I thought about using the templates to construct a jason object that I would than return to my js component ..

**Comment by dwightgunning** [comment]
Are you by chance using django-rest-framework or vanilla Django views?

**Comment by japrogramer** [comment]
Im using vanilla views, but im in the process of switching keverything over to graphene.

**Comment by dwightgunning** [comment]
I think best to focus on the stream-django side of the interaction here. The frontend react will likely flow naturally once you have a consistent way to render and return your enriched activities.

To go back to the original question about reading activity streams and enriching with foreign key or many-to-many relationships, you can always build Django views that represent the 'resource' (in the REST sense; e.g. an enriched Stream activity + Django model data) and emit a JSON object (with application/json content type).

Our twitter clone example shows a series of Django CBVs which emit HTML templates but which can easily be adapted to emit JSON: https://github.com/GetStream/django_twitter/blob/master/stream_twitter/views.py
