### ISSUE TITLE
i get errors when installing stream_django on windows

### ISSUE THREAD

**Issue by johnzeus14** [GetStream/stream-django#81]
hello I tried installing stream and I get errors in the last part of setup.py pycrodomex

**Comment by johnzeus14** [comment]
see
Command "c:\users\zeus\desktop\resume-back\env\scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\zeus\\AppData\\Local\\Temp\\pip-install-_stge40m\\pycryptodomex\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\zeus\AppData\Local\Temp\pip-record-ioqe3bw_\install-record.txt --single-version-externally-managed --compile --install-headers c:\users\zeus\desktop\resume-back\env\include\site\python3.7\pycryptodomex" failed with error code 1 in C:\Users\zeus\AppData\Local\Temp\pip-install-_stge40m\pycryptodomex\

**Comment by johnzeus14** [comment]
see
Command "c:\users\zeus\desktop\resume-back\env\scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\zeus\\AppData\\Local\\Temp\\pip-install-_stge40m\\pycryptodomex\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\zeus\AppData\Local\Temp\pip-record-ioqe3bw_\install-record.txt --single-version-externally-managed --compile --install-headers c:\users\zeus\desktop\resume-back\env\include\site\python3.7\pycryptodomex" failed with error code 1 in C:\Users\zeus\AppData\Local\Temp\pip-install-_stge40m\pycryptodomex\

**Comment by johnzeus14** [comment]
okay i understand i solved it..stream does not support python 3.7

**Comment by pterk** [comment]
@johnzeus14 I've just merged a fix for python3.7 tests (and travis conf. 🙄). Can you try if that fixes the issue on windows?

**Comment by pterk** [comment]
Closing this for now. Feel free to re-open if the issue persists.

**Comment by johnzeus14** [comment]
okay no problem i used python 6
