### ISSUE TITLE
Is there a plan to add reactions?

### ISSUE THREAD

**Issue by JJZolper** [GetStream/stream-django#91]
I'm unable to find how to use reactions. Seems like it was forgotten and not added when it was added to stream-python.

**Comment by tbarbugli** [comment]
You can use the Stream client within Django as well; is there anything you miss on Django for reactions?

**Comment by JJZolper** [comment]
Thanks for responding Tom. I saw the example for retrieving a feed with reactions with the py client was:

# read bob's timeline and include most recent reactions to all activities and their total count
client.feed("timeline", "bob").get(reactions={"recent": True, "counts": True})

# read bob's timeline and include most recent reactions to all activities and her own reactions
client.feed("timeline", "bob").get(
    reactions={"own": True, "recent": True, "counts": True}, user_id="bob"
)

I'm using the client within django to add them to an activity but in order to retrieve I was needing:

        feeds = feed_manager.get_feed('cityposts', generate_sub_feed(city, topic))
        enricher = Enrich()
        activities = feeds.get(reactions={"recent": True, "counts": True})['results']
        enriched_activities = enricher.enrich_activities(activities)

Something along those lines. Which is not using the client so I was wondering if that was something that would work? I'm still trying to make Stream work with REST as I still have that Django REST backend and the Vue.js front end. I can't just use the python client only because eventually the objects have to be serialized and returned from the API. I want the whole feed not just the reactions from a feed. I want my posts and the comments (reactions) that are under the posts.

**Comment by JJZolper** [comment]
I think I found them doing it the way above... I made a stupid mistake.

**Comment by rickhonda** [comment]
Quick question, what are you importing in order for this to work? 

```
    stream_client.reactions.add(
        "comment", self.kwargs['postid'], user_id=str(request.user.pk), data={"body": request.data['body']}
    )
```

I would assume: 

`import stream`

or 

`stream_client = stream.connect('appropriate keys')
`
??
