### ISSUE TITLE
Crypto library

### ISSUE THREAD

**Issue by Nyamador** [GetStream/stream-django#93]
Having issues installing the stream django package due to errors from pycrypto ..I'm using python 3.6, please help..Is there a way pycrypto can be replaced with pycryptodome?

**Comment by Nyamador** [comment]
I'm closing this issue due to the lack of support.

**Comment by ferhatelmas** [comment]
Ah sorry, it seems it is missed.

Could you describe what you did and which error you got? Then I will check and try to help here.
