### ISSUE TITLE
Support for Django v3.0 and up?

### ISSUE THREAD

**Issue by kiran-capoor94** [GetStream/stream-django#95]
When installing stream-django, it uninstalls Django 3.0.4 and in turn install Django 2.2.11. 
Is Django 3+ not supported?

**Comment by tbarbugli** [comment]
just checked, we need to upgrade the requirements for the library and re-release, beside that nothing else needs to be done to support Django 3 (also good time to drop ancient Python 3.x from build if needed)

**Comment by soulshake** [comment]
I see you have a [release for stream-django 1.6.2](https://github.com/GetStream/stream-django/releases/tag/1.6.2) but [pypi](https://pypi.org/project/stream-django/) is still serving 1.6.1.

Are you planning to release 1.6.2 on pypi?
Thanks!

**Comment by ferhatelmas** [comment]
Yes, we will take care of it today/tomorrow.

**Comment by pterk** [comment]
Apologies for the further delay. I just uploaded the release.
