### ISSUE TITLE
How is 'unfollowing' supposed to be handled?

### ISSUE THREAD

**Issue by lggwettmann** [GetStream/stream-django#96]
Hey guys,

I'm still marvelously confused by stream-django tbh. I am trying to solve 'unfollowing feeds'. Once someone unfollows another user, I delete my FollowUser-model instance in the django database and send a feedmanager.unfollow_user() - in the user's timeline, there is still the following activity.

Am I suppose to delete that following activity and what would the foreign_id be for that? Seems like it's not set in the feedmanager when following the user? Or am I supposed to not delete the model instance and just mark it as 'archived' or something similar?

If I don't do anything, I get an activity from stream which can't be enriched cause my model instance has been deleted - and I don't seem to be able to find any information on how this is supposed to be solved in any of the docs...

Any help and pointers are highly appreciated!

**Comment by tbarbugli** [comment]
can you share the relevant python code here?

**Comment by lggwettmann** [comment]
Hey @tbarbugli and thanks for your fast response. I basically took the code from the feedmananger.unfollow_user() method and use it in my signal after deleting the UserFollow instance.
```
def unfollow_team_feed(sender, instance, **kwargs):  
	news_feeds = feed_manager.get_news_feeds(instance.user.id)
	target_feed = feed_manager.get_feed('team', instance.target.id)
	for feed in news_feeds.values():
		feed.unfollow(target_feed.slug, target_feed.user_id)
		feed.remove_activity(foreign_id=activity.create_model_reference(instance))
signals.post_delete.connect(unfollow_team_feed, sender=TeamFollow)
```

**Comment by lggwettmann** [comment]
I even added a foreign_id into the extra data on feed.follow() (see below) but the foreign_id doesn't show up in the 'follow' activity in the getstream dashboard - and means it also doesn't get deleted when following the team.
```
  def follow_team_feed(self, follow: 'feeds.TeamFollow'):
        news_feeds = self.get_news_feeds(follow.user.pk)
        target_feed = self.get_feed('team', follow.target.pk)
        foreign_id = f'feeds.TeamFollow:{follow.pk}'
        for feed in news_feeds.values():
            feed.follow(target_feed.slug, target_feed.user_id, foreign_id=foreign_id)
```

**Comment by lggwettmann** [comment]
Could you help me out here @tbarbugli or should I contact Stream Support? I'm literally stuck on this and have no idea how to proceed. Is the path I am following even the correct one regarding unfollow handling?

**Comment by tbarbugli** [comment]
follow relationships don't have a foreign_id, only activities do

`feed.follow(target_feed.slug, target_feed.user_id, foreign_id=foreign_id)`

creates a follow relationship, not an activities. if you read the `feed` feed afterwards you will see the activities from `target_feed`

**Comment by tbarbugli** [comment]
going back to the first problem; if you unfollow a feed you activities are removed automatically. can you check the `origin` field for the activity that you expect to be gone? the origin field tell you where the activity comes from (None means it was added directly)

**Comment by lggwettmann** [comment]
Thanks @tbarbugli. I was not sure if the follows could have foreign_ids and didn't find any documentation on it. As it was the closest thing to solve the issue, that's why I tried. ;)

Indeed, the activities are removed, but not the 'follow' itself. The origin field for the 'follow' activity is None. But I am not aware of adding an extra activity. I'm using the code for ```follow_team_feed``` posted above.

This is an example of a follow activity that does not get deleted when unfollowing a team or any other kind of feed:
<img width="1219" alt="Screenshot 2020-04-07 10 53 47" src="https://user-images.githubusercontent.com/4527829/78650029-a4123f00-78be-11ea-9d1b-6a86813824d4.png">

**Comment by lggwettmann** [comment]
Any idea about this anyone? :)

**Comment by ferhatelmas** [comment]
@lggwettmann sorry again sliding this issue. Could you pass me your app id so that I can check what you're doing. If you have additional finding in the meantime, let me know too.

To make it clear, @tbarbugli  was explaining what you were doing wrong with following line:

```py
feed.follow(target_feed.slug, target_feed.user_id, foreign_id=foreign_id)
```

This is wrong. `foreign_id` is a field on activity and irrelevant to `follow` relationship and it will be ignored silently.

**Comment by lggwettmann** [comment]
Hey @ferhatelmas,

and thanks so much for taking the time to look into this. Good that you clarified it. I just tried it and understood that ```foreign_id``` is ignored for ```follow``` relationships 👍🏻

My question is more architectural on how one 'deletes' follow-relationships or how 'not following anymore' is supposed to be handled by a system using Stream? My app_id is 22042. :)

**Comment by ferhatelmas** [comment]
Ok, I checked. We're mixing the vocabulary here. 

Follow in stream means get activities from other feeds to my feed and they don't create an activity of an action in the feed automatically (i.e follow in this case). This is your application logic and actually as far as I understand you shouldn't remove them when somebody unfollows a feed because it's still an update on the feed itself according to what you're doing. 

On the other hand, if you want to get rid of them, you should delete them by yourself because they aren't added by follow so they won't be removed by unfollow.

If you explain the goal of your application, I am happy to suggest feed groups and flow to achieve it.

Thanks for your patience.

**Comment by ferhatelmas** [comment]
@lggwettmann I assume we're here and closing. Please let me know otherwise if any help is needed. 

Thanks for leveraging the API. Looking forward to what you're going to build with it. :100:
